### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sidharrth2002** [sidharrth2002/neural-style-transfer#1]
- [ ] #3

- [ ] #4

<img src="https://user-images.githubusercontent.com/53941721/137067183-33337ab0-6fb5-4998-bb35-b402360c803c.png" width=300 />

- [ ] #5

- [ ] #6
https://towardsdatascience.com/python-for-art-fast-neural-style-transfer-using-tensorflow-2-d5e7662061be

**Comment by TheCornelius** [comment]
All done yeet
